name: Deploy DynamoDB CRUD API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js v20.x
      uses: actions/setup-node@v3
      with:
        node-version: v20.x

    - name: Install dependencies
      run: yarn install

    - name: Install Serverless Framework v3
      run: npm install -g serverless@3

    - name: Serverless Deploy
      run: serverless deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
